participant main.cpp as main
participant ccache.cpp as ccache
participant mainoptions.cpp as parseOpt
activate main
main -> ccache ++ : main
ccache -> ccache ++ #Green : ccache_main
note right of ccache
    判断是否是 形如ccache -v 的ccache cmd操作
end note
ccache -> ccache ++ #Gray : process_main_option
ccache -> parseOpt ++ 
note right of parseOpt
    解析命令参数并且执行
end note

return  EXIT 

ccache --> main : EXIT
ccache --
note right of ccache
    如果不是操作命令，则开始生成cache
end note
ccache -> ccache ++ #Gold: cache_comliation 
ccache --
ccache --
return EXIT



