@startuml directHash
participant ccache.cpp as main
participant Storage.cpp as storage
participant Manifest.cpp as manifest
participant Result.cpp as result

main --> main ++ #Pink: cache_compilation
main --> main ++ #Gold : do_cache_compilation
main --> main ++ #FFFF00 : hash_common_info
main--
main --> main ++ #FFFF00 : calculate_result_and_manifest_key
main --> main : hash.digest
note right of main
        diget当前hash缓存区得到hash值,即Manifest路径
end note

main --> storage ++ #DarkSalmon:ctx.storage.get
note right of storage #FFAAAA
        从stroage中成功获取Manifest
end note
return 成功获取到Manifest

main --> manifest ++ #Green: read_manifest
return  返回Manifest中的内容
main --> manifest ++ #Green: look_up_result_digest

manifest --> manifest :result_matches
note right of manifest
        从Manifest中最新生成的Result进行匹配头文件，
        如果所有头文件都存在且hash值能匹配上，则使用该reulst。
end note
return 返回result 路径
main--

main --> main ++ #FFFF00: from_cache
main --> storage ++ #DarkSalmon:ctx.storage.get
note right of storage #FFAAAA
        从storage中成功获取Result;
        Manifest和Result都能直接获取，直连命中
end note
return  成功获取

main --> result ++: result_reader.read
result --> result :read_entry
note right of result
        读取result文件内容，将result中压缩的.o还原至ctx保存输出路径。
end note

return
main--
main--
main --> main ++ #Gold: ctx.storage.primary.increment_statistics
note right of main
        记录为Direct命中情况，保存到status中，后续查看整体命中情况。
end note
main--

@enduml
